// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: w9kDmnz3CKYi6zHEAKmNbm
// Component: xGKBFPSHosiC
import * as React from "react";
import Head from "next/head";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: w9kDmnz3CKYi6zHEAKmNbm/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: xGKBFPSHosiC/css
import Line7Icon from "./icons/PlasmicIcon__Line7"; // plasmic-import: beAxZVoAH6O/icon
import Polygon11Icon from "./icons/PlasmicIcon__Polygon11"; // plasmic-import: -5MIM2YkZyo/icon
import Line1Icon from "./icons/PlasmicIcon__Line1"; // plasmic-import: sBsYiWxqhW0/icon
import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: Nm5z41289yC/icon
import Path316Icon from "./icons/PlasmicIcon__Path316"; // plasmic-import: 3wgllrNWoMv/icon
import Path1793Icon from "./icons/PlasmicIcon__Path1793"; // plasmic-import: GncO2zHEXtZ/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"dealDetail"}
            data-plasmic-override={overrides.dealDetail}
            className={classNames(projectcss.all, sty.dealDetail)}
          >
            <div
              data-plasmic-name={"component159"}
              data-plasmic-override={overrides.component159}
              className={classNames(projectcss.all, sty.component159)}
            >
              <div
                data-plasmic-name={"rectangle866"}
                data-plasmic-override={overrides.rectangle866}
                className={classNames(projectcss.all, sty.rectangle866)}
              />

              <div
                data-plasmic-name={"image7"}
                data-plasmic-override={overrides.image7}
                className={classNames(projectcss.all, sty.image7)}
              />

              <Line7Icon
                className={classNames(projectcss.all, sty.svg__ggjIq)}
                role={"img"}
              />

              <Line7Icon
                className={classNames(projectcss.all, sty.svg__uWpLe)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cgiud
                )}
              >
                {"Food\nTravel\nExperience\nOriginals"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fpuzQ
                )}
              >
                {"Haute Streets\nOriginals\nExclusives\nPodcast"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bryN3
                )}
              >
                {"About Us\nAdvertise\nEditorial Policy\nTerms of Use\nPress"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x6PnT
                )}
              >
                {"Join The #CTSquad!"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9I27
                )}
              >
                {"Join The #HauteSquad!"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__j5NYl
                )}
              >
                {"Copyright © CurlyTales All rights reserved."}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4TOlF
                )}
              >
                {"Copyright © Hauterrfly All rights reserved."}
              </div>

              <div
                data-plasmic-name={"rectangle867"}
                data-plasmic-override={overrides.rectangle867}
                className={classNames(projectcss.all, sty.rectangle867)}
              />

              <div
                data-plasmic-name={"rectangle868"}
                data-plasmic-override={overrides.rectangle868}
                className={classNames(projectcss.all, sty.rectangle868)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4C3Z
                )}
              >
                {"Subscribe"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__exQq3
                )}
              >
                {"            "}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hrgKy
                )}
              >
                {"Email"}
              </div>
            </div>

            <div
              data-plasmic-name={"component78"}
              data-plasmic-override={overrides.component78}
              className={classNames(projectcss.all, sty.component78)}
            >
              <div
                data-plasmic-name={"image1"}
                data-plasmic-override={overrides.image1}
                className={classNames(projectcss.all, sty.image1)}
              />

              <div
                data-plasmic-name={"group65"}
                data-plasmic-override={overrides.group65}
                className={classNames(projectcss.all, sty.group65)}
              >
                <div
                  data-plasmic-name={"group64"}
                  data-plasmic-override={overrides.group64}
                  className={classNames(projectcss.all, sty.group64)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qbBD
                    )}
                  >
                    {"India"}
                  </div>

                  <Polygon11Icon
                    className={classNames(projectcss.all, sty.svg__iEtya)}
                    role={"img"}
                  />
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tHxI0
                  )}
                >
                  {"Subscribe"}
                </div>
              </div>

              <Line1Icon
                className={classNames(projectcss.all, sty.svg__gpQQc)}
                role={"img"}
              />

              <Line2Icon
                className={classNames(projectcss.all, sty.svg__fGRm)}
                role={"img"}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___4A5C
                )}
              >
                {"Home     Trending     Videos     Deals     Epic in my city"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6UyPg
                )}
              >
                {"Food     Travel     Experience"}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rpFps
                )}
              >
                {""}
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__djuJc
                )}
              >
                {""}
              </div>

              <div
                data-plasmic-name={"group274"}
                data-plasmic-override={overrides.group274}
                className={classNames(projectcss.all, sty.group274)}
              >
                <div
                  data-plasmic-name={"group158"}
                  data-plasmic-override={overrides.group158}
                  className={classNames(projectcss.all, sty.group158)}
                >
                  <div
                    data-plasmic-name={"rectangle232"}
                    data-plasmic-override={overrides.rectangle232}
                    className={classNames(projectcss.all, sty.rectangle232)}
                  />

                  <div
                    data-plasmic-name={"rectangle236"}
                    data-plasmic-override={overrides.rectangle236}
                    className={classNames(projectcss.all, sty.rectangle236)}
                  />

                  <div
                    data-plasmic-name={"rectangle235"}
                    data-plasmic-override={overrides.rectangle235}
                    className={classNames(projectcss.all, sty.rectangle235)}
                  />

                  <div
                    data-plasmic-name={"rectangle233"}
                    data-plasmic-override={overrides.rectangle233}
                    className={classNames(projectcss.all, sty.rectangle233)}
                  />

                  <div
                    data-plasmic-name={"rectangle238"}
                    data-plasmic-override={overrides.rectangle238}
                    className={classNames(projectcss.all, sty.rectangle238)}
                  />

                  <div
                    data-plasmic-name={"rectangle237"}
                    data-plasmic-override={overrides.rectangle237}
                    className={classNames(projectcss.all, sty.rectangle237)}
                  />
                </div>

                <div
                  data-plasmic-name={"iconDiscoverCtQuickies"}
                  data-plasmic-override={overrides.iconDiscoverCtQuickies}
                  className={classNames(
                    projectcss.all,
                    sty.iconDiscoverCtQuickies
                  )}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6W5WC
                    )}
                  >
                    {"CT"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lk6T
                    )}
                  >
                    {"Quickies"}
                  </div>
                </div>
              </div>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__bvEr
                )}
              >
                {"            "}
              </div>
            </div>

            <div
              data-plasmic-name={"repeatGrid2"}
              data-plasmic-override={overrides.repeatGrid2}
              className={classNames(projectcss.all, sty.repeatGrid2)}
            >
              <div
                data-plasmic-name={"group264"}
                data-plasmic-override={overrides.group264}
                className={classNames(projectcss.all, sty.group264)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vOrAg
                  )}
                >
                  {"Couple Staycation At ₹8400 Including Taxes at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle368"}
                  data-plasmic-override={overrides.rectangle368}
                  className={classNames(projectcss.all, sty.rectangle368)}
                />

                <div
                  data-plasmic-name={"group285"}
                  data-plasmic-override={overrides.group285}
                  className={classNames(projectcss.all, sty.group285)}
                >
                  <div
                    data-plasmic-name={"rectangle98"}
                    data-plasmic-override={overrides.rectangle98}
                    className={classNames(projectcss.all, sty.rectangle98)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dqDz
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__r4P9W
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__fj5GZ)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group265"}
                data-plasmic-override={overrides.group265}
                className={classNames(projectcss.all, sty.group265)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nVcwp
                  )}
                >
                  {"Enjoy A Staycation For Two At Just ₹8999 at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle369"}
                  data-plasmic-override={overrides.rectangle369}
                  className={classNames(projectcss.all, sty.rectangle369)}
                />

                <div
                  data-plasmic-name={"group286"}
                  data-plasmic-override={overrides.group286}
                  className={classNames(projectcss.all, sty.group286)}
                >
                  <div
                    data-plasmic-name={"rectangle99"}
                    data-plasmic-override={overrides.rectangle99}
                    className={classNames(projectcss.all, sty.rectangle99)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hClOp
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__upca
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__taoR)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group266"}
                data-plasmic-override={overrides.group266}
                className={classNames(projectcss.all, sty.group266)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__umQtT
                  )}
                >
                  {"Experience Fly Dining Experience At Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle370"}
                  data-plasmic-override={overrides.rectangle370}
                  className={classNames(projectcss.all, sty.rectangle370)}
                />

                <div
                  data-plasmic-name={"group287"}
                  data-plasmic-override={overrides.group287}
                  className={classNames(projectcss.all, sty.group287)}
                >
                  <div
                    data-plasmic-name={"rectangle100"}
                    data-plasmic-override={overrides.rectangle100}
                    className={classNames(projectcss.all, sty.rectangle100)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kpfN6
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iIeyv
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cGdgy)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group267"}
                data-plasmic-override={overrides.group267}
                className={classNames(projectcss.all, sty.group267)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__y8BJi
                  )}
                >
                  {
                    "3N/4D stay in suite for just ₹12,999/- including breakfast and dinner"
                  }
                </div>

                <div
                  data-plasmic-name={"rectangle371"}
                  data-plasmic-override={overrides.rectangle371}
                  className={classNames(projectcss.all, sty.rectangle371)}
                />

                <div
                  data-plasmic-name={"group288"}
                  data-plasmic-override={overrides.group288}
                  className={classNames(projectcss.all, sty.group288)}
                >
                  <div
                    data-plasmic-name={"rectangle101"}
                    data-plasmic-override={overrides.rectangle101}
                    className={classNames(projectcss.all, sty.rectangle101)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a9SZr
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__caqsT
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qQhid)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>
            </div>

            <div
              data-plasmic-name={"repeatGrid43"}
              data-plasmic-override={overrides.repeatGrid43}
              className={classNames(projectcss.all, sty.repeatGrid43)}
            >
              <div
                data-plasmic-name={"group268"}
                data-plasmic-override={overrides.group268}
                className={classNames(projectcss.all, sty.group268)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kfXkd
                  )}
                >
                  {"Couple Staycation At ₹8400 Including Taxes at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle372"}
                  data-plasmic-override={overrides.rectangle372}
                  className={classNames(projectcss.all, sty.rectangle372)}
                />

                <div
                  data-plasmic-name={"group289"}
                  data-plasmic-override={overrides.group289}
                  className={classNames(projectcss.all, sty.group289)}
                >
                  <div
                    data-plasmic-name={"rectangle102"}
                    data-plasmic-override={overrides.rectangle102}
                    className={classNames(projectcss.all, sty.rectangle102)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kJbEg
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___12Rrw
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6IFcl)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group269"}
                data-plasmic-override={overrides.group269}
                className={classNames(projectcss.all, sty.group269)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__l8Sv6
                  )}
                >
                  {"Couple Staycation At ₹8400 Including Taxes at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle373"}
                  data-plasmic-override={overrides.rectangle373}
                  className={classNames(projectcss.all, sty.rectangle373)}
                />

                <div
                  data-plasmic-name={"group290"}
                  data-plasmic-override={overrides.group290}
                  className={classNames(projectcss.all, sty.group290)}
                >
                  <div
                    data-plasmic-name={"rectangle103"}
                    data-plasmic-override={overrides.rectangle103}
                    className={classNames(projectcss.all, sty.rectangle103)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3LEjJ
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__keTl1
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__lEnJa)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group270"}
                data-plasmic-override={overrides.group270}
                className={classNames(projectcss.all, sty.group270)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__izmJi
                  )}
                >
                  {"Couple Staycation At ₹8400 Including Taxes at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle374"}
                  data-plasmic-override={overrides.rectangle374}
                  className={classNames(projectcss.all, sty.rectangle374)}
                />

                <div
                  data-plasmic-name={"group291"}
                  data-plasmic-override={overrides.group291}
                  className={classNames(projectcss.all, sty.group291)}
                >
                  <div
                    data-plasmic-name={"rectangle104"}
                    data-plasmic-override={overrides.rectangle104}
                    className={classNames(projectcss.all, sty.rectangle104)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iRuIi
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iJwb3
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hCxH9)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>

              <div
                data-plasmic-name={"group271"}
                data-plasmic-override={overrides.group271}
                className={classNames(projectcss.all, sty.group271)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mdeFg
                  )}
                >
                  {"Couple Staycation At ₹8400 Including Taxes at Yu Hotel"}
                </div>

                <div
                  data-plasmic-name={"rectangle375"}
                  data-plasmic-override={overrides.rectangle375}
                  className={classNames(projectcss.all, sty.rectangle375)}
                />

                <div
                  data-plasmic-name={"group292"}
                  data-plasmic-override={overrides.group292}
                  className={classNames(projectcss.all, sty.group292)}
                >
                  <div
                    data-plasmic-name={"rectangle105"}
                    data-plasmic-override={overrides.rectangle105}
                    className={classNames(projectcss.all, sty.rectangle105)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tN1Nc
                    )}
                  >
                    {"View Deals"}
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jmVMg
                  )}
                >
                  {"42.5k"}
                </div>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___2Njbz)}
                  displayHeight={"19px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"22px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/blank_project/images/_3916579.svg",
                    fullWidth: 22,
                    fullHeight: 19,
                    aspectRatio: 1.157895
                  }}
                />
              </div>
            </div>

            <Path316Icon
              className={classNames(projectcss.all, sty.svg__zlxKg)}
              role={"img"}
            />

            <div
              data-plasmic-name={"group275"}
              data-plasmic-override={overrides.group275}
              className={classNames(projectcss.all, sty.group275)}
            >
              <div
                data-plasmic-name={"maskGroup1"}
                data-plasmic-override={overrides.maskGroup1}
                className={classNames(projectcss.all, sty.maskGroup1)}
              >
                <div
                  data-plasmic-name={"image42"}
                  data-plasmic-override={overrides.image42}
                  className={classNames(projectcss.all, sty.image42)}
                />
              </div>
            </div>

            <Path1793Icon
              className={classNames(projectcss.all, sty.svg__cIvl)}
              role={"img"}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ha2Md
              )}
            >
              {"Other deals from Yu Hotel"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zukxf
              )}
            >
              {"Other deals from Goa"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__npt6W
              )}
            >
              {
                "YU Hotel, Goa: 2N/3D Stay In The Heart Of North Goa With A Rooftop Jacuzzi At ₹10,999"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__kbCGw
              )}
            >
              {"Curly Tales Exclusive Offer"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__u5Ci0
              )}
            >
              {"Enjoy A Wholesome Meals And A Relaxing Stay"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__qewZn
              )}
            >
              {"Inclusions:"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__c3F0T
              )}
            >
              {"Inclusions:"}
            </div>

            <div
              data-plasmic-name={
                "awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW"
              }
              data-plasmic-override={
                overrides.awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW
              )}
            >
              {
                "Away from the hustle and bustle of city life, this resort will keep you close to nature. The rooms equipped with all the modern facilities offer next-level relaxation and comfort. The Deluxe Room with a cosy balcony faces the lush green garden. And guess what? With the Curly Tales exclusive offer, you can book a ‘couple stay’ at just ₹11,000 for 2 nights inclusive of all meals and taxes.\n\n3D/2N Deluxe Room (Weekdays): Stay for two including breakfast, lunch and dinner at ₹11,000 \n\n3D/2N Deluxe Room (Weekends): Stay for two including breakfast, lunch and dinner at ₹12,500 "
              }
            </div>

            <div
              data-plasmic-name={"image2"}
              data-plasmic-override={overrides.image2}
              className={classNames(projectcss.all, sty.image2)}
            />

            <div
              data-plasmic-name={
                "theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG"
              }
              data-plasmic-override={
                overrides.theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAg
              )}
            >
              {
                "The food is delicious, warm, and homely. The breakfast spread is sure to satisfy you with its After you’ve enjoyed a wholesome meal, relax in the spacious pool or go for a massage in the spa. This resort is sure to make you feel pampered. If you are on a getaway with your kids, you can spend some fun time in the gaming room or play some outdoor games.\n\nWhat’s more, the resort is ideal for weddings, corporate conferences, and get-togethers with a huge group of friends & family. So, what are you waiting for? Book your getaway now!"
              }
            </div>

            <div
              data-plasmic-name={
                "ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP"
              }
              data-plasmic-override={
                overrides.ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP
              }
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP
              )}
            >
              {
                "If you are looking for a getaway with your loved ones, we have got you a perfect find. Set amid lush greenery, this resort makes an idyllic getaway for all those seeking a luxurious refuge from their daily life. This 15-acre paradise located in Silvassa, promises a truly exclusive experience that goes beyond the conventional limits of hospitality and comfort."
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ni4Xk
              )}
            >
              {
                "- Complimentary breakfast for two\n- Complimentary lunch for two\n- Complimentary dinner for two\n- Complimentary high tea\n- All taxes included"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ynle7
              )}
            >
              {" Candolim Bardez, Goa, India"}
            </div>

            <div
              data-plasmic-name={"group669"}
              data-plasmic-override={overrides.group669}
              className={classNames(projectcss.all, sty.group669)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__rUzLx)}
                displayHeight={"100px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"180px"}
                loading={"lazy"}
                src={{
                  src: "/plasmic/blank_project/images/group659.svg",
                  fullWidth: 180,
                  fullHeight: 100,
                  aspectRatio: 1.8
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zFmNu
                )}
              >
                {"32"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9WiOn
              )}
            >
              {"Daily\nBreakfast"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tw8Io
              )}
            >
              {"In-house\nGym"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__faMc8
              )}
            >
              {"Complimentary\nGlass of wine"}
            </div>

            <div
              data-plasmic-name={"rectangle1072"}
              data-plasmic-override={overrides.rectangle1072}
              className={classNames(projectcss.all, sty.rectangle1072)}
            />

            <div
              data-plasmic-name={"rectangle1073"}
              data-plasmic-override={overrides.rectangle1073}
              className={classNames(projectcss.all, sty.rectangle1073)}
            />

            <div
              data-plasmic-name={"rectangle1074"}
              data-plasmic-override={overrides.rectangle1074}
              className={classNames(projectcss.all, sty.rectangle1074)}
            />

            <div
              data-plasmic-name={"rectangle1075"}
              data-plasmic-override={overrides.rectangle1075}
              className={classNames(projectcss.all, sty.rectangle1075)}
            />

            <div
              data-plasmic-name={"rectangle1076"}
              data-plasmic-override={overrides.rectangle1076}
              className={classNames(projectcss.all, sty.rectangle1076)}
            />

            <div
              data-plasmic-name={"rectangle1077"}
              data-plasmic-override={overrides.rectangle1077}
              className={classNames(projectcss.all, sty.rectangle1077)}
            />

            <div
              data-plasmic-name={"image100"}
              data-plasmic-override={overrides.image100}
              className={classNames(projectcss.all, sty.image100)}
            />

            <div
              data-plasmic-name={"image101"}
              data-plasmic-override={overrides.image101}
              className={classNames(projectcss.all, sty.image101)}
            />

            <div
              data-plasmic-name={"image102"}
              data-plasmic-override={overrides.image102}
              className={classNames(projectcss.all, sty.image102)}
            />

            <div
              data-plasmic-name={"rectangle1082"}
              data-plasmic-override={overrides.rectangle1082}
              className={classNames(projectcss.all, sty.rectangle1082)}
            />

            <div
              data-plasmic-name={"rectangle376"}
              data-plasmic-override={overrides.rectangle376}
              className={classNames(projectcss.all, sty.rectangle376)}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__dRjrV
              )}
            >
              {"DLX Rooms"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__nbHc
              )}
            >
              {"₹11000 (₹14000) / 2 adults only"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__iggZq
              )}
            >
              {
                "Inclusions:\nComplimentary breakfast for two\nComplimentary lunch for two\nComplimentary dinner for two\nComplimentary high tea\nAll taxes included"
              }
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__y1Bd7
              )}
            >
              {"Price"}
            </div>

            <div
              data-plasmic-name={"group120"}
              data-plasmic-override={overrides.group120}
              className={classNames(projectcss.all, sty.group120)}
            >
              <div
                data-plasmic-name={"rectangle132"}
                data-plasmic-override={overrides.rectangle132}
                className={classNames(projectcss.all, sty.rectangle132)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__r5Cf
                )}
              >
                {"Book Now - ₹10,999"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__o0T2A
              )}
            >
              {"Stay - 15 Jan, 2021 - 17 Jan, 2021 (2N/3D)"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cDzgx
              )}
            >
              {"Change"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "dealDetail",
    "component159",
    "rectangle866",
    "image7",
    "rectangle867",
    "rectangle868",
    "component78",
    "image1",
    "group65",
    "group64",
    "group274",
    "group158",
    "rectangle232",
    "rectangle236",
    "rectangle235",
    "rectangle233",
    "rectangle238",
    "rectangle237",
    "iconDiscoverCtQuickies",
    "repeatGrid2",
    "group264",
    "rectangle368",
    "group285",
    "rectangle98",
    "group265",
    "rectangle369",
    "group286",
    "rectangle99",
    "group266",
    "rectangle370",
    "group287",
    "rectangle100",
    "group267",
    "rectangle371",
    "group288",
    "rectangle101",
    "repeatGrid43",
    "group268",
    "rectangle372",
    "group289",
    "rectangle102",
    "group269",
    "rectangle373",
    "group290",
    "rectangle103",
    "group270",
    "rectangle374",
    "group291",
    "rectangle104",
    "group271",
    "rectangle375",
    "group292",
    "rectangle105",
    "group275",
    "maskGroup1",
    "image42",
    "awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW",
    "image2",
    "theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG",
    "ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP",
    "group669",
    "rectangle1072",
    "rectangle1073",
    "rectangle1074",
    "rectangle1075",
    "rectangle1076",
    "rectangle1077",
    "image100",
    "image101",
    "image102",
    "rectangle1082",
    "rectangle376",
    "group120",
    "rectangle132"
  ],

  dealDetail: [
    "dealDetail",
    "component159",
    "rectangle866",
    "image7",
    "rectangle867",
    "rectangle868",
    "component78",
    "image1",
    "group65",
    "group64",
    "group274",
    "group158",
    "rectangle232",
    "rectangle236",
    "rectangle235",
    "rectangle233",
    "rectangle238",
    "rectangle237",
    "iconDiscoverCtQuickies",
    "repeatGrid2",
    "group264",
    "rectangle368",
    "group285",
    "rectangle98",
    "group265",
    "rectangle369",
    "group286",
    "rectangle99",
    "group266",
    "rectangle370",
    "group287",
    "rectangle100",
    "group267",
    "rectangle371",
    "group288",
    "rectangle101",
    "repeatGrid43",
    "group268",
    "rectangle372",
    "group289",
    "rectangle102",
    "group269",
    "rectangle373",
    "group290",
    "rectangle103",
    "group270",
    "rectangle374",
    "group291",
    "rectangle104",
    "group271",
    "rectangle375",
    "group292",
    "rectangle105",
    "group275",
    "maskGroup1",
    "image42",
    "awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW",
    "image2",
    "theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG",
    "ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP",
    "group669",
    "rectangle1072",
    "rectangle1073",
    "rectangle1074",
    "rectangle1075",
    "rectangle1076",
    "rectangle1077",
    "image100",
    "image101",
    "image102",
    "rectangle1082",
    "rectangle376",
    "group120",
    "rectangle132"
  ],

  component159: [
    "component159",
    "rectangle866",
    "image7",
    "rectangle867",
    "rectangle868"
  ],

  rectangle866: ["rectangle866"],
  image7: ["image7"],
  rectangle867: ["rectangle867"],
  rectangle868: ["rectangle868"],
  component78: [
    "component78",
    "image1",
    "group65",
    "group64",
    "group274",
    "group158",
    "rectangle232",
    "rectangle236",
    "rectangle235",
    "rectangle233",
    "rectangle238",
    "rectangle237",
    "iconDiscoverCtQuickies"
  ],

  image1: ["image1"],
  group65: ["group65", "group64"],
  group64: ["group64"],
  group274: [
    "group274",
    "group158",
    "rectangle232",
    "rectangle236",
    "rectangle235",
    "rectangle233",
    "rectangle238",
    "rectangle237",
    "iconDiscoverCtQuickies"
  ],

  group158: [
    "group158",
    "rectangle232",
    "rectangle236",
    "rectangle235",
    "rectangle233",
    "rectangle238",
    "rectangle237"
  ],

  rectangle232: ["rectangle232"],
  rectangle236: ["rectangle236"],
  rectangle235: ["rectangle235"],
  rectangle233: ["rectangle233"],
  rectangle238: ["rectangle238"],
  rectangle237: ["rectangle237"],
  iconDiscoverCtQuickies: ["iconDiscoverCtQuickies"],
  repeatGrid2: [
    "repeatGrid2",
    "group264",
    "rectangle368",
    "group285",
    "rectangle98",
    "group265",
    "rectangle369",
    "group286",
    "rectangle99",
    "group266",
    "rectangle370",
    "group287",
    "rectangle100",
    "group267",
    "rectangle371",
    "group288",
    "rectangle101"
  ],

  group264: ["group264", "rectangle368", "group285", "rectangle98"],
  rectangle368: ["rectangle368"],
  group285: ["group285", "rectangle98"],
  rectangle98: ["rectangle98"],
  group265: ["group265", "rectangle369", "group286", "rectangle99"],
  rectangle369: ["rectangle369"],
  group286: ["group286", "rectangle99"],
  rectangle99: ["rectangle99"],
  group266: ["group266", "rectangle370", "group287", "rectangle100"],
  rectangle370: ["rectangle370"],
  group287: ["group287", "rectangle100"],
  rectangle100: ["rectangle100"],
  group267: ["group267", "rectangle371", "group288", "rectangle101"],
  rectangle371: ["rectangle371"],
  group288: ["group288", "rectangle101"],
  rectangle101: ["rectangle101"],
  repeatGrid43: [
    "repeatGrid43",
    "group268",
    "rectangle372",
    "group289",
    "rectangle102",
    "group269",
    "rectangle373",
    "group290",
    "rectangle103",
    "group270",
    "rectangle374",
    "group291",
    "rectangle104",
    "group271",
    "rectangle375",
    "group292",
    "rectangle105"
  ],

  group268: ["group268", "rectangle372", "group289", "rectangle102"],
  rectangle372: ["rectangle372"],
  group289: ["group289", "rectangle102"],
  rectangle102: ["rectangle102"],
  group269: ["group269", "rectangle373", "group290", "rectangle103"],
  rectangle373: ["rectangle373"],
  group290: ["group290", "rectangle103"],
  rectangle103: ["rectangle103"],
  group270: ["group270", "rectangle374", "group291", "rectangle104"],
  rectangle374: ["rectangle374"],
  group291: ["group291", "rectangle104"],
  rectangle104: ["rectangle104"],
  group271: ["group271", "rectangle375", "group292", "rectangle105"],
  rectangle375: ["rectangle375"],
  group292: ["group292", "rectangle105"],
  rectangle105: ["rectangle105"],
  group275: ["group275", "maskGroup1", "image42"],
  maskGroup1: ["maskGroup1", "image42"],
  image42: ["image42"],
  awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW:
    [
      "awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW"
    ],

  image2: ["image2"],
  theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG:
    [
      "theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG"
    ],

  ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP:
    [
      "ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP"
    ],

  group669: ["group669"],
  rectangle1072: ["rectangle1072"],
  rectangle1073: ["rectangle1073"],
  rectangle1074: ["rectangle1074"],
  rectangle1075: ["rectangle1075"],
  rectangle1076: ["rectangle1076"],
  rectangle1077: ["rectangle1077"],
  image100: ["image100"],
  image101: ["image101"],
  image102: ["image102"],
  rectangle1082: ["rectangle1082"],
  rectangle376: ["rectangle376"],
  group120: ["group120", "rectangle132"],
  rectangle132: ["rectangle132"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    dealDetail: makeNodeComponent("dealDetail"),
    component159: makeNodeComponent("component159"),
    rectangle866: makeNodeComponent("rectangle866"),
    image7: makeNodeComponent("image7"),
    rectangle867: makeNodeComponent("rectangle867"),
    rectangle868: makeNodeComponent("rectangle868"),
    component78: makeNodeComponent("component78"),
    image1: makeNodeComponent("image1"),
    group65: makeNodeComponent("group65"),
    group64: makeNodeComponent("group64"),
    group274: makeNodeComponent("group274"),
    group158: makeNodeComponent("group158"),
    rectangle232: makeNodeComponent("rectangle232"),
    rectangle236: makeNodeComponent("rectangle236"),
    rectangle235: makeNodeComponent("rectangle235"),
    rectangle233: makeNodeComponent("rectangle233"),
    rectangle238: makeNodeComponent("rectangle238"),
    rectangle237: makeNodeComponent("rectangle237"),
    iconDiscoverCtQuickies: makeNodeComponent("iconDiscoverCtQuickies"),
    repeatGrid2: makeNodeComponent("repeatGrid2"),
    group264: makeNodeComponent("group264"),
    rectangle368: makeNodeComponent("rectangle368"),
    group285: makeNodeComponent("group285"),
    rectangle98: makeNodeComponent("rectangle98"),
    group265: makeNodeComponent("group265"),
    rectangle369: makeNodeComponent("rectangle369"),
    group286: makeNodeComponent("group286"),
    rectangle99: makeNodeComponent("rectangle99"),
    group266: makeNodeComponent("group266"),
    rectangle370: makeNodeComponent("rectangle370"),
    group287: makeNodeComponent("group287"),
    rectangle100: makeNodeComponent("rectangle100"),
    group267: makeNodeComponent("group267"),
    rectangle371: makeNodeComponent("rectangle371"),
    group288: makeNodeComponent("group288"),
    rectangle101: makeNodeComponent("rectangle101"),
    repeatGrid43: makeNodeComponent("repeatGrid43"),
    group268: makeNodeComponent("group268"),
    rectangle372: makeNodeComponent("rectangle372"),
    group289: makeNodeComponent("group289"),
    rectangle102: makeNodeComponent("rectangle102"),
    group269: makeNodeComponent("group269"),
    rectangle373: makeNodeComponent("rectangle373"),
    group290: makeNodeComponent("group290"),
    rectangle103: makeNodeComponent("rectangle103"),
    group270: makeNodeComponent("group270"),
    rectangle374: makeNodeComponent("rectangle374"),
    group291: makeNodeComponent("group291"),
    rectangle104: makeNodeComponent("rectangle104"),
    group271: makeNodeComponent("group271"),
    rectangle375: makeNodeComponent("rectangle375"),
    group292: makeNodeComponent("group292"),
    rectangle105: makeNodeComponent("rectangle105"),
    group275: makeNodeComponent("group275"),
    maskGroup1: makeNodeComponent("maskGroup1"),
    image42: makeNodeComponent("image42"),
    awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW:
      makeNodeComponent(
        "awayFromTheHustleAndBustleOfCityLifeThisResortWillKeepYouCloseToNatureTheRoomsEquippedWithAllTheModernFacilitiesOfferNextLevelRelaxationAndComfortTheDeluxeRoomWithACosyBalconyFacesTheLushGreenGardenAndGuessW"
      ),

    image2: makeNodeComponent("image2"),
    theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG:
      makeNodeComponent(
        "theFoodIsDeliciousWarmAndHomelyTheBreakfastSpreadIsSureToSatisfyYouWithItsAfterYouveEnjoyedAWholesomeMealRelaxInTheSpaciousPoolOrGoForAMassageInTheSpaThisResortIsSureToMakeYouFeelPamperedIfYouAreOnAG"
      ),

    ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP:
      makeNodeComponent(
        "ifYouAreLookingForAGetawayWithYourLovedOnesWeHaveGotYouAPerfectFindSetAmidLushGreeneryThisResortMakesAnIdyllicGetawayForAllThoseSeekingALuxuriousRefugeFromTheirDailyLifeThis15AcreParadiseLocatedInSilvassaP"
      ),

    group669: makeNodeComponent("group669"),
    rectangle1072: makeNodeComponent("rectangle1072"),
    rectangle1073: makeNodeComponent("rectangle1073"),
    rectangle1074: makeNodeComponent("rectangle1074"),
    rectangle1075: makeNodeComponent("rectangle1075"),
    rectangle1076: makeNodeComponent("rectangle1076"),
    rectangle1077: makeNodeComponent("rectangle1077"),
    image100: makeNodeComponent("image100"),
    image101: makeNodeComponent("image101"),
    image102: makeNodeComponent("image102"),
    rectangle1082: makeNodeComponent("rectangle1082"),
    rectangle376: makeNodeComponent("rectangle376"),
    group120: makeNodeComponent("group120"),
    rectangle132: makeNodeComponent("rectangle132"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
